name: feed_fm
description: Flutter plugin for FeedFM integration.
version: 0.0.1
author: Your Name <your.email@example.com>
homepage: https://yourhomepage.com
environment:
  sdk: ">=3.0.0 <4.0.0"

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: FeedFmPlugin
      android:
        package: com.byteztech.feed_fm
        pluginClass: FeedFmPlugin

dependencies:
  flutter:
    sdk: flutter
